<?php include 'admin_header.php'; ?>
<head><title>Add Movie</title></head>
<?php
echo "    <form action=\"admin_movie_add.php\" method=\"post\" role=\"form\" class=\"form-horizontal\" >\n";
echo "      <fieldset>\n";
echo "      <legend><a name=\"Addmovie\"><h2>Add Movie</h2></a></legend>\n";
echo "\n";
echo "      <div class=\"form-group\">\n";
echo "      <div class=\"col-sm-4\">\n";
echo "      <input class=\"form-control\" id=\"ex2\" type=\"text\" name=\"title\" placeholder=\"Title\" required>\n";
echo "    </div>\n";
echo "    </div>\n";
echo "    <div class=\"form-group\">\n";
echo "          <div class=\"col-sm-4\">\n";
echo "\n";
echo "            <input class=\"form-control\" id=\"ex2\" type=\"file\"\n";
echo "                name=\"image\" accept=\"image/*\" alt=\"Input\"\n";
echo "                placeholder=\"Image\" data-toggle=\"tooltip\" title=\"Poster's Movie\">\n";
echo "            </div>\n";
echo "            </div>\n";
echo "\n";
echo "\n";
echo "            <div class=\"form-group\">\n";
echo "              <div class=\"col-sm-4\">\n";
echo "  <select class=\"form-control\" id=\"sel1\" data-toggle=\"tooltip\" title=\"Category\" name=\"category\" required>\n";
echo "            <option></option>\n";
echo "            <option>Action</option>\n";
echo "            <option>Horror</option>\n";
echo "            <option>Comedy</option>\n";
echo "          </select>\n";
echo "              </div>\n";
echo "              </div>\n";
echo "              <script>\n";
echo "          $(document).ready(function(){\n";
echo "              $('[data-toggle=\"tooltip\"]').tooltip();\n";
echo "          });\n";
echo "          </script>\n";
echo "          <div class=\"form-group\">\n";
echo "          <div class=\"col-sm-4\">\n";
echo "   <textarea class=\"form-control\" name=\"movDesc\"
rows=\"5\" cols=\"55\" placeholder=\"Description\"></textarea>";
echo "    </div>\n";
echo "      </div>\n";
echo "\n";
echo "      <div class=\"form-group\">\n";
echo "      <div class=\"col-sm-4\">\n";
echo "    <input class=\"form-control\" id=\"ex2\" type=\"date\" name=\"pubDate\"\n";
echo "          placeholder=\"Publish date\" data-toggle=\"tooltip\" title=\"Publish Date\" required  >\n";
echo "      </div>\n";
echo "      </div>\n";
   echo "<!-- Trigger the modal with a button -->\n";
   echo "  <button type=\"button\" class=\"btn btn-info btn-lg\" data-toggle=\"modal\" data-target=\"#myModal\">ADD</button>\n";
   echo "\n";
   echo "  <!-- Modal -->\n";
   echo "  <div class=\"modal fade\" id=\"myModal\" role=\"dialog\">\n";
   echo "    <div class=\"modal-dialog\">\n";
   echo "    \n";
   echo "      <!-- Modal content-->\n";
   echo "      <div class=\"modal-content\">\n";
   echo "        \n";
   echo "        <div class=\"modal-body\">\n";
   echo "          <p>Are you sure?</p>\n";
   echo "        </div>\n";
   echo "        <div class=\"modal-footer\">\n";
   echo "        <button type=\"submit\" class=\"btn btn-default\" >Ok</button>\n";
   echo "          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\n";
   echo " \n";
   echo "        </div>\n";
   echo " \n";
   echo "     \n";
   echo "     \n";
   echo "      </div>\n";
   echo "      \n";
   echo "    </div>\n";
   echo "  </div>\n";
   echo "  \n";
echo "    <input class=\"btn btn-primary\" type=\"reset\" value=\"Clear\">\n";
echo "  </fieldset>\n";
echo "  </form>\n";
echo "\n";
echo "\n";
echo "\n";
?>
<?php include 'admin_footer.php'; ?>
